# permissions for end users to edit orchestrators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: orchestrator-operator
    app.kubernetes.io/managed-by: kustomize
  name: orchestrator-editor-role
rules:
- apiGroups:
  - orchestrator.parodos.dev
  resources:
  - orchestrators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orchestrator.parodos.dev
  resources:
  - orchestrators/status
  verbs:
  - get
