# permissions for end users to view orchestrators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: orchestrator-operator
    app.kubernetes.io/managed-by: kustomize
  name: orchestrator-viewer
rules:
- apiGroups:
  - rhdh.redhat.com
  resources:
  - orchestrators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rhdh.redhat.com
  resources:
  - orchestrators/status
  verbs:
  - get
