---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - namespaces
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.knative.dev
  resources:
  - knativeeventings
  - knativeservings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - catalogsources
  - clusterserviceversions
  - operatorgroups
  - subscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - rhdh.redhat.com
  resources:
  - backstages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rhdh.redhat.com
  resources:
  - orchestrators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rhdh.redhat.com
  resources:
  - orchestrators/finalizers
  verbs:
  - update
- apiGroups:
  - rhdh.redhat.com
  resources:
  - orchestrators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sonataflow.org
  resources:
  - sonataflowclusterplatforms
  - sonataflowplatforms
  - sonataflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
