---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - orchestrator.parodos.dev
  resources:
  - orchestrators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orchestrator.parodos.dev
  resources:
  - orchestrators/finalizers
  verbs:
  - update
- apiGroups:
  - orchestrator.parodos.dev
  resources:
  - orchestrators/status
  verbs:
  - get
  - patch
  - update
