apiVersion: orchestrator.parodos.dev/v1alpha1
kind: Orchestrator
metadata:
  labels:
    app.kubernetes.io/name: orchestrator-operator
    app.kubernetes.io/managed-by: kustomize
  name: orchestrator-sample
spec:
  # TODO(user): Add fields here
