apiVersion: orchestrator.parodos.dev/v1alpha1
kind: Orchestrator
metadata:
  labels:
    app.kubernetes.io/name: orchestrator-operator
    app.kubernetes.io/managed-by: kustomize
  name: orchestrator-sample
spec:
  sonataFlowOperator:
    isReleaseCandidate: false # Indicates RC builds should be used by the chart to install Sonataflow
    enabled: true # whether the operator should be deployed by the operator
    subscription:
      namespace: openshift-serverless-logic # namespace where the operator should be deployed
      channel: alpha # channel of an operator package to subscribe to
      installPlanApproval: Automatic # whether the update should be installed automatically
      name: logic-operator-rhel8 # name of the operator package
      sourceName: redhat-operators # name of the catalog source
      startingCSV: logic-operator-rhel8.v1.33.0 # The initial version of the operator
  orchestrator:
    namespace: "sonataflow-infra"
    sonataFlowPlatform:
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
